---
- name: Prepare all nodes for AAP
  hosts: all
  become: true
  tasks:
    # Install required packages
    - name: Install required packages
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - git
          - vim
          - wget
          - curl
          - sudo
          - podman
          - firewalld
        state: present

    # Enable and start firewalld
    - name: Enable and start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    # Configure firewalld rules
    - name: Configure firewalld for AAP
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - http
        - https
        - ssh
        - postgresql

    # Update /etc/hosts
    - name: Update /etc/hosts for hostname resolution
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.56.10 db.local"
        - "192.168.56.11 pah.local"
        - "192.168.56.12 controller.local"
        - "192.168.56.13 worker.local"

    # Create the rhel user
    - name: Create the rhel user
      ansible.builtin.user:
        name: rhel
        password: "{{ 'redhat' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: wheel
        append: true

    # Add rhel user to sudoers
    - name: Add rhel user to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "rhel ALL=(ALL) NOPASSWD:ALL"
        state: present

- name: Set up SSH keys for passwordless authentication
  hosts: controller
  become: true
  tasks:
    # Generate SSH key pair for rhel
    - name: Generate an SSH key pair for rhel if it doesn't exist
      ansible.builtin.command:
        cmd: ssh-keygen -t rsa -b 2048 -f /home/rhel/.ssh/id_rsa -q -N ""
        creates: /home/rhel/.ssh/id_rsa
      become_user: rhel

    # Retrieve the public SSH key
    - name: Retrieve the public SSH key for rhel
      ansible.builtin.slurp:
        src: /home/rhel/.ssh/id_rsa.pub
      register: ssh_public_key
      become_user: rhel

- name: Distribute SSH public key to managed nodes
  hosts: all:!controller
  become: true
  tasks:
    # Ensure .ssh directory exists
    - name: Ensure .ssh directory exists for rhel user
      ansible.builtin.file:
        path: /home/rhel/.ssh
        state: directory
        mode: '0700'
        owner: rhel
        group: rhel

    # Add the controller's public key to authorized_keys
    - name: Add the controller's public key to authorized_keys
      ansible.builtin.copy:
        dest: /home/rhel/.ssh/authorized_keys
        content: "{{ ssh_public_key['content'] | b64decode }}"
        mode: '0600'
        owner: rhel
        group: rhel

    # Set correct permissions for .ssh directory
    - name: Set correct permissions for .ssh directory
      ansible.builtin.file:
        path: /home/rhel/.ssh
        state: directory
        mode: '0700'
        owner: rhel
        group: rhel
