---
- name: Deploy GitLab CE with Podman (replicating docker-compose.yml example)
  hosts: automationcontroller
  become: yes

  vars:
    gitlab_image: "docker.io/gitlab/gitlab-ce:latest"
    container_name: "gitlab.example.com"
    container_hostname: "gitlab.example.com"
    gitlab_home: "{{ lookup('env', 'GITLAB_HOME') | default('/srv/gitlab.example.com', true) }}"
    shm_size: "256m"
    restart_policy: "unless-stopped"
    # Adjust the external_url to reflect the new port (8080)
    gitlab_external_url: "http://{{ container_hostname }}:8080"

  tasks:
    - name: Install Podman and Postfix (if not already installed)
      dnf:
        name:
          - podman
          - postfix
        state: present
        update_cache: yes

    - name: Ensure Postfix is running and enabled
      service:
        name: postfix
        state: started
        enabled: yes

    - name: Create GitLab home directory
      file:
        path: "{{ gitlab_home }}"
        state: directory
        mode: '0755'

    - name: Create GitLab config directory
      file:
        path: "{{ gitlab_home }}/config"
        state: directory
        mode: '0755'

    - name: Create GitLab logs directory
      file:
        path: "{{ gitlab_home }}/logs"
        state: directory
        mode: '0755'

    - name: Create GitLab data directory
      file:
        path: "{{ gitlab_home }}/data"
        state: directory
        mode: '0755'

    - name: Restore SELinux contexts on GitLab directories
      command: "restorecon -R {{ gitlab_home }}"
      when: ansible_selinux.status == "enabled"

    - name: Remove existing GitLab container if present
      command: "podman rm -f {{ container_name }}"
      ignore_errors: yes

    - name: Run GitLab CE container with Podman
      command: >
        podman run -d
        --name {{ container_name }}
        --hostname {{ container_hostname }}
        --env GITLAB_OMNIBUS_CONFIG="external_url '{{ gitlab_external_url }}'"
        --publish 8080:80
        --publish 8443:443
        --publish 2222:22
        --restart {{ restart_policy }}
        --volume {{ gitlab_home }}/config:/etc/gitlab:Z
        --volume {{ gitlab_home }}/logs:/var/log/gitlab:Z
        --volume {{ gitlab_home }}/data:/var/opt/gitlab:Z
        --shm-size {{ shm_size }}
        {{ gitlab_image }}
      args:
        warn: false

# To stop and delete this instance: sudo podman stop gitlab-ee && sudo podman rm gitlab-ce
