# gitlab-docker.yml

# On RHEL, you need Podman, Python3 pip, and podman-compose to use `podman compose`.
# Example commands (run as root or via sudo):
#
# yum install -y python3-pip
# pip3 install podman-compose
#
# Also configure your firewall to allow GitLab's ports:
# firewall-cmd --permanent --add-port=8080/tcp
# firewall-cmd --permanent --add-port=8443/tcp
# firewall-cmd --permanent --add-port=2222/tcp
# firewall-cmd --reload
#
# Once installed and configured, run:
# podman compose -f ./gitlab-docker.yml up -d
#
---
services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    container_name: gitlab.example.com
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8080'
    ports:
      - '8080:80'
      - '8443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    restart: unless-stopped
